apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent2
  labels:
    name: agent2
spec:
  selector:
    matchLabels:
      app: agent2
  replicas: 1
  template:
    metadata:
      labels:
        app: agent2
    spec:
      containers:
        - name: agent2
          image: kerberos/agent:3.2.3
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: AGENT_NAME
              value: str
            - name: AGENT_CAPTURE_IPCAMERA_RTSP
              value: rtsp://192.168.1.155:8554/cam
            # find full list of environment variables here: https://github.com/kerberos-io/agent#override-with-environment-variables
---
apiVersion: v1
kind: Service
metadata:
  name: agent2-svc
  labels:
    name: agent2-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.204
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: agent2
