apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-xabits
  namespace: xabits
  annotations:
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/dns01-provider: cloudflare
spec:
  ingressClassName: traefik
  rules:
  - host: xabits.xaf.world
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xabits-service
            port:
              number: 80
  tls:
    - hosts:
        - xabits.xaf.world
      secretName: xabits-tls
