apiVersion: v1
kind: Service
metadata:
  name: xabits-service
  namespace: xabits
spec:
  type: ClusterIP
  selector:
    app: habit-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
