- name: Install node_exporter on Raspberry Pis
  hosts: raspberry_pis
  become: yes
  tasks:
    - name: Create a user for node_exporter
      user:
        name: node_exporter
        shell: /usr/sbin/nologin

    - name: Download node_exporter binary
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-armv7.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract node_exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Move binary to /usr/local/bin
      copy:
        remote_src: yes
        src: /opt/node_exporter-1.9.1.linux-armv7/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0755'

    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=default.target

    - name: Reload systemd and enable/start node_exporter
      systemd:
        daemon_reload: yes
        name: node_exporter
        enabled: yes
        state: started
